### PR TITLE
Update idempotent-examples.md

### PR DESCRIPTION
**Pull request by Tycholiz**
## Description
Add an edge-case idempotent example for renaming enum values

### CODE REVIEW

**Review by benjie — APPROVED** [review]

**Comment by benjie** [comment]
I’m surprised this file is not being formatted by prettier.

**Comment by benjie** [comment]
Thanks 🙏 🙌

**Comment by Tycholiz** [comment]
Ya not sure! I made the commit right in GitHub, should it have formatted it as well?

**Comment by benjie** [comment]
More that it should be set up in CI to validate. I’ll fix formatting when I add CI.

**Pull request merged**
